# Generated by Django 6.0.7 on 2026-08-04 21:14

import devices.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.CharField(help_text='Identificador único de fábrica del ESP32', max_length=32, unique=True)),
                ('codigo', models.CharField(default=devices.models.generar_codigo_vinculo, max_length=4)),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando vinculación'), ('vinculado', 'Vinculado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_vinculo', to='devices.device')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
