# Generated by Django 6.0.7 on 2026-08-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_solicitudvinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='etiqueta_off',
            field=models.CharField(blank=True, default='OFF', help_text="Solo para sensores tipo 'Estado'. Texto para el valor inactivo (ej: OFF, Abajo, Vacío).", max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='etiqueta_on',
            field=models.CharField(blank=True, default='ON', help_text="Solo para sensores tipo 'Estado'. Texto para el valor activo (ej: ON, Arriba, Lleno).", max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='tipo_sensor',
            field=models.CharField(choices=[('generico', 'Genérico (sin unidad)'), ('temperatura', 'Temperatura (°C)'), ('corriente', 'Corriente (A)'), ('binario', 'Estado (ON/OFF)')], default='generico', max_length=20),
        ),
    ]
