# Generated by Django 6.0.7 on 2026-08-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_etiqueta_off_device_etiqueta_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='intervalo_offline_segundos',
            field=models.PositiveIntegerField(default=120, help_text='Si no llega ninguna lectura en este tiempo (segundos), el dispositivo pasa a mostrarse como Offline. Un ESP32 que manda cada 10s puede usar el default (120s). Si viene de un script/puente que manda cada 5 min, poné algo como 600-900 para darle margen.'),
        ),
    ]
