# Generated by Django 6.0.7 on 2026-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_intervalo_offline_segundos'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='grupo',
            field=models.CharField(blank=True, help_text='Opcional. Agrupá dispositivos que dependen del mismo origen (ej: la misma PC puente, el mismo edificio). Si TODOS los dispositivos de un grupo quedan offline al mismo tiempo, Lumbre lo interpreta como un corte general (de luz o de red) en ese origen, en vez de fallas individuales, y te avisa de forma diferenciada.', max_length=100),
        ),
    ]
