# Generated by Django 6.0.7 on 2026-08-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tipo_sensor',
            field=models.CharField(choices=[('generico', 'Genérico (sin unidad)'), ('temperatura', 'Temperatura (°C)'), ('corriente', 'Corriente (A)'), ('db', 'Decibeles (dB)'), ('binario', 'Estado (ON/OFF)')], default='generico', max_length=20),
        ),
    ]
