# Generated by Django 6.0.7 on 2026-08-11 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_device_tipo_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Línea A - Tablero principal', max_length=100)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='devices.device')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddField(
            model_name='lectura',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='devices.sesionmedicion'),
        ),
    ]
