# Generated by Django 6.0.7 on 2026-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_sesionmedicion_lectura_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionmedicion',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Si lo completás, la sesión se finaliza sola después de este tiempo (cronómetro).', null=True),
        ),
    ]
