# Generated by Django 6.0.7 on 2026-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_sesionmedicion_duracion_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=100)),
                ('device_id_original', models.UUIDField(blank=True, help_text='El ID que tenía el Device cuando existía (referencia, no FK).', null=True)),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('archivado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lectura archivada',
                'verbose_name_plural': 'Historial de sensores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nombre_sensor', '-timestamp'], name='devices_his_nombre__061899_idx')],
            },
        ),
    ]
